### ISSUE TITLE
Admins should be able to export/backup the DB.

### ISSUE THREAD

**Issue by srenfo** [dorpvom/mettinizr#43]
We do not want to lose user balances in case of data loss.

Bonus points if we can figure out a way to do this automatically.

**Comment by dorpvom** [comment]
Obviously sounds like a rest functionality ^^
Then it can be cron'd

**Comment by dorpvom** [comment]
Backup Script is ready from #61 , rollback pending

**Comment by dorpvom** [comment]
Solved by combination of #61 and #62
